### ISSUE TITLE
Schema overwritten when 2 projects have the same name

### ISSUE THREAD

**Issue by Carael** [SwissLife-OSS/Confix#122]
While migrating a solution that have 2 project with the same name:
- src/Api/Host
- src/Bff/Host

After running "dotnet confix reload" in ".confix/schemas" folder only one Host.schema.json file is created.

**Comment by PascalSenn** [comment]
Fixed in https://github.com/SwissLife-OSS/Confix/releases/tag/0.1.0-preview.26
