### ISSUE TITLE
confix reload lock

### ISSUE THREAD

**Issue by RohrerF** [SwissLife-OSS/Confix#83]
`confix reload` should have an option to make it explode if there are any changes to the confix files. This option is useful to validate all necessary files have been checked in and are up-to-date in the ci pipeline

**Comment by RohrerF** [comment]
it should work similar to `npm ci`

https://docs.npmjs.com/cli/v9/commands/npm-ci

**Comment by PascalSenn** [comment]
this no longer needed https://github.com/SwissLife-OSS/Confix/pull/82
